
<form action="<?= $this->escape($this->form->getAction()) ?>"
      method="<?= $this->escape($this->form->getMethod()) ?>">

<fieldset>
    <legend>Editing Client</legend>

    <?= $this->form->clientID ?>
    <?= $this->form->name ?>
    <?= $this->form->homePhone ?>
    <?= $this->form->homePhone ?>
    <?= $this->form->caseID ?>
    <?= $this->form->status ?>
    <?= $this->form->visitDate ?>
    <?= $this->form->miles ?>
    <?= $this->form->hours ?>
    <?= $this->form->caseNeed ?>
    <?= $this->form->amount ?>
    <?= $this->form->opendedUserID ?>
    <?= $this->form->openedDate ?>
    <?= $this->form->referral ?>
    <?= $this->form->referredReason ?>
    <?= $this->form->referralDate ?>
    <?= $this->form->commentDate ?>
    <?= $this->form->comment ?>
    
</fieldset>

<?= $this->form->submit ?>
</form>