
<form action="<?= $this->escape($this->element->getAction()) ?>"
      method="<?= $this->escape($this->element->getMethod()) ?>">

<fieldset>
    <table>
    	<tbody>
    		<tr><td>
			    <?php echo $this->element->clientID ?>
			    </td><td>
			    <?php echo $this->element->name ?>
			    </td><td>
			    <?php echo $this->element->homePhone ?>
			    </td></tr><tr><td>
			    <?php echo $this->element->caseID ?>
			    </td><td>
			    <?php echo $this->element->openedDate ?>
			    </td><td>
			    <?php echo $this->element->status ?>
			    </td></tr><tr><td>
			    <?php echo $this->element->visitDate ?>
			    </td><td>
			    <?php echo $this->element->miles ?>
			    </td><td>
			    <?php echo $this->element->hours ?>
			    </td></tr><tr><td>
			    <?php echo $this->element->caseNeed ?>
			    </td><td>
			    <?php echo $this->element->amount ?>
			    </td></tr><tr><td>
			    <?php echo $this->element->opendedUserID ?>
			    </td></tr><tr><td>
			    <?php echo $this->element->referral ?>
			    </td><td>
			    <?php echo $this->element->referredReason ?>
			    </td><td>
			    <?php echo $this->element->referralDate ?>
			    </td></tr><tr><td>
			    <?php echo $this->element->commentDate ?>
			    </td><td>
			    <?php echo $this->element->comment ?>
				</td></tr><tr><td>
				<?php echo $this->element->editCase ?>
			    </td><td>
		    </tbody>
	    </table>
</fieldset>

<?php echo $this->element->submit ?>
</form>