<fieldset>
    <legend>Household History:</legend>
    <div class=search-results>
        <table class='search-results'>
            <?php
            
			$rowStripeClass = (!(isset($this->i) && $this->i % 2)) ? 'even' : 'odd';
						
			foreach (array_values($this->history) as $i => $history):?>
				<tr class="search-result <?php echo $rowStripeClass; ?>">
		    	<th class="search-cell bot first">Householder</th>
		    	<td class="search-cell bot"><?php echo $this->escape($this->client->getFullName()); ?></td>
		    	<th class="search-cell bot first">Address</th>
		    	<td colspan=5 class="search-cell bot"><?php echo $this->escape($this->client->getCurrentAddr()->getFullAddr()); ?></td>
				</tr>
				<?php echo $this->partial('partial/viewHouseholdHistory.phtml', array('i' => $i, 'history' => $history));
			endforeach; ?>
			
        </table>
    </div>
</fieldset>