<?php
if (isset($this->latitude) && isset($this->longitude)) {
    $this->headScript()->captureStart();
?>
$(function() {
    drawMap($('#map'), new google.maps.LatLng(<?php echo Zend_Json::encode($this->latitude); ?>, <?php echo Zend_Json::encode($this->longitude); ?>));
});
<?php
    $this->headScript()->captureEnd();
}
?>
<div class=row-fluid>
    <div class=span6>
    <?php echo $this->form; ?>
    </div>

    <?php if (isset($this->latitude) && isset($this->longitude)) { ?>
    <div class=span6><div class=well><div id=map>
        <noscript>JavaScript must be enabled to display maps.</noscript>
    </div></div></div>
    <?php } ?>
</div>
