<?php
if (empty($this->cases)) {
?>
<p>You currently have no open cases.</p>
<?php
} else {
?>
<fieldset>
    <legend>Your currently open cases:</legend>
    <div class=search-results>
    <table class=search-results>
    <?php
    $this->partialLoop()->setObjectKey('case');
    echo $this->partialLoop('partial/searchResultCase.phtml', $this->cases);
    ?>
    </table>
    </div>
</fieldset>
<?php
}
?>
