<?php
$viewClientUrl = $this->baseUrl(App_Resources::MEMBER,
    '/viewClient/id/' . urlencode($this->case->getClient()->getId()));
?>
<p>Viewing activity summary for case having ID <?php echo $this->escape($this->case->getId()); ?>.</p>

<div class=search-results><table class=search-results>
<?php
echo $this->partial('partial/searchResultClient.phtml', array(
    'client' => $this->case->getClient(),
));
?>
</table></div>
<?php echo $this->form; ?>
