<?php
$viewClientUrl = $this->baseUrl(App_Resources::MEMBER,
    '/viewCase/id/' . urlencode($this->case->getClient()->getId()));
?>
<p>Viewing summary for case ID <?php echo $this->escape($this->case->getId()); ?>.</p>

<fieldset>
    <legend>Client information:</legend>
    <div class=search-results><table class=search-results>
    <?php
    echo $this->partial('partial/searchResultClient.phtml', array(
        'client' => $this->case->getClient(),
    ));
    ?>
    </table></div>
</fieldset>
<div class='form-horizontal twocol'>
    <fieldset class=row-fluid>
        <legend>General case information:</legend>

        <div class=span6><div class=control-group>
            <span class=control-label>Client ID</span>
            <div class=controls><a href=<?php echo $this->escape($viewClientUrl); ?>><?php echo $this->escape($this->case->getId()); ?></a></div>
        </div></div>

        <div class=span6>
            <span class=control-label>Client Name</span>
            <div class=control-group><div class=controls>
                <?php echo $this->escape($this->case->getClient()->getFullName()); ?>
            </div></div>
        </div>

        <div class=span6>
            <span class=control-label>Case ID</span>
            <div class=control-group><div class=controls>
                <?php echo $this->escape($this->case->getId()); ?>
            </div></div>
        </div>
    </fieldset>
</div>
