<?php $baseUrl = new Zend_View_Helper_BaseUrl();
    $format = new App_Formatting();?>
 
<table>
    <tr>
        <td><h2><center>St. Vincent de Paul&nbsp;&nbsp;</center></h2></td><td>&nbsp;</td>
        <td>
            <form action="<?php echo $baseUrl->baseUrl('/report/clientpdf/')?>" method=post>
            <input type="hidden" name="clientid" value="<?php echo $this->client->getId() ?>">
            <input type="submit" value="Generate PDF">
            </form>
        </td>      
    </tr>
    <tr>
        <td><h4><center>Client Information Report&nbsp;</center></h4></td><td>&nbsp;</td><td>&nbsp;</td>
    </tr>
    <tr>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td>&nbsp;Client ID:&nbsp;<?php echo $this->client->getId() ?>&nbsp;</td>
        <td>&nbsp;First Name:&nbsp;<?php echo $this->client->getFirstName() ?>&nbsp;</td>
        <td>&nbsp;Last Name:&nbsp;<?php echo $this->client->getLastName() ?>&nbsp;</td>
    </tr>
    <tr>
        <td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
    </tr>
    <tr>
        <td>&nbsp;Birth Date:&nbsp;<?php echo $this->client->getBirthDate() ?>&nbsp;</td>
        <td>&nbsp;Marital Status:&nbsp;<?php if($this->client->isMarried())
                                    {echo "Married";}else{echo "Single";} ?>&nbsp;</td>
        <td>&nbsp;Spouse:&nbsp;<?php if($this->client->isMarried())
                                    {echo $this->client->getSpouse()->getFullName();} ?>&nbsp;</td>
    </tr>
    <tr>        
        <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Client ID:&nbsp;<?php echo $this->client->getId() ?>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td>&nbsp;Cell Number:&nbsp;<?php echo $this->client->getFormattedCellPhone() ?>&nbsp;</td>
        <td>&nbsp;Home Number:&nbsp;<?php echo $this->client->getFormattedHomePhone() ?>&nbsp;</td>
        <td>&nbsp;Work Number:&nbsp;<?php echo $this->client->getFormattedWorkPhone() ?>&nbsp;</td>
    </tr>
    <tr>        
        <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Client Name:&nbsp;<?php echo $this->client->getFullName() ?> &nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td>&nbsp;Date Created:&nbsp;<?php echo $this->client->getCreatedDate() ?>&nbsp;</td>
        <td>&nbsp;Parish:&nbsp;<?php echo $this->client->getParish() ?>&nbsp;</td>
        <td>&nbsp;Veteran:&nbsp;<?php if($this->client->isVeteran()){echo "Yes";}else{echo "No";} ?>&nbsp;</td>
    </tr>
    <tr>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Spouse:&nbsp;<?php if($this->client->isMarried())
                                    {echo $this->escape($this->client->getSpouse()->getFullName());} ?>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
    </tr>
    <tr>        
        <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Current Address:&nbsp;<?php echo $this->client->getCurrentAddr()->getStreet()?>
        &nbsp;<?php echo $this->client->getCurrentAddr()->getCity() ?>
        &nbsp;<?php echo $this->client->getCurrentAddr()->getState() ?>
        ,&nbsp; <?php echo $this->client->getCurrentAddr()->getZip() ?>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td>&nbsp;Street:&nbsp;<?php echo $this->client->getCurrentAddr()->getStreet() ?>&nbsp;</td>
        <td>&nbsp;Apartment:&nbsp;<?php echo $this->client->getCurrentAddr()->getApt() ?>&nbsp;</td>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td>&nbsp;City:&nbsp;<?php echo $this->client->getCurrentAddr()->getCity() ?>&nbsp;</td>
        <td>&nbsp;State:&nbsp;<?php echo $this->client->getCurrentAddr()->getState() ?>&nbsp;</td>
        <td>&nbsp;Zip Code:&nbsp;<?php echo $this->client->getCurrentAddr()->getZip() ?>&nbsp;</td>
    </tr>
</table>
