<?php
    header("Content-type: application/vnd.ms-excel");
    header("Content-Disposition: attachment; filename=excel.xls");
?>
<html>
    <table border="1"><font >
        <tr>
            <td align="center" colspan="11" ><strong>St. Vincent dePaul Society -- Financial Assistance Fund</strong></td>
        </tr>
        <tr>
            <td align="center" colspan="11">213 Main Street, West Chicago, IL 60185
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Phone:&nbsp;630-293-9755&nbsp;&nbsp;Fax:&nbsp;630-293-9881</td>
        </tr
        <tr>        
            <td align="center" colspan="11"><strong>Reimbursement Report</strong></td>           
        </tr>
        <tr></tr>
        <tr>        
            <td><strong>Conference:</strong></td>
            <td colspan="6" align="center"><strong>St. Rapheal:</strong></td>
            <td><strong>Conference Case #:</strong></td>
            <td> </td><td>&nbsp;</td><td>&nbsp;</td>
        </tr>
        <tr>
            <td align="center" colspan="11" bgcolor="#00FF00">Assistance Given To</td>
        </tr>
        <tr>        
            <td>Last Name:</td>
            <td colspan="2"><?php echo $this->client->getLastName()   ?></td>
            <td>First Name:</td>
            <td colspan="2"><?php echo $this->client->getFirstName()   ?> </td>
            <td>Spouse Name:</td>
            <td colspan="2"><?php if($this->client->isMarried())
                                    {echo $this->client->getSpouse()->getFullName();} ?> </td>
            <td>&nbsp;</td><td>&nbsp;</td>
        </tr>
        <tr></tr>
        <tr>        
            <td>Street:</td>
            <td colspan="3"><?php echo $this->client->getCurrentAddr()->getStreet() ?> </td>
            <td>City/State:</td>
            <td colspan="2"><?php echo $this->client->getCurrentAddr()->getCity();
                    echo ", "; echo $this->client->getCurrentAddr()->getState(); ?> </td>
            <td>Zip:</td>
            <td><?php echo $this->client->getCurrentAddr()->getZip() ?> </td><td>&nbsp;</td>
        </tr>
        <tr></tr>
        <tr>        
            <td>Phone #:</td>
            <td colspan="2"><?php echo $this->client->getFormattedCellPhone() ?> </td>
            <td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
            <td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
        </tr>
        <tr></tr>
        <tr>        
            <td>SVDP Member:</td>
            <td colspan="2"><?php echo $this->request[0]->getUser()  ?> </td>
            <td>Contact #:</td>
            <td colspan="2"> </td>
            <td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
        </tr>
        <tr></tr>
        <tr>        
            <td>Home Visit?:</td>
            <td>&nbsp;&nbsp;X&nbsp;&nbsp;&nbsp;</td>
            <td>Phone Interview?</td>
            <td> </td>
            <td>Date:</td>
            <td> </td>
            <td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
        </tr>
        <tr>
            <td align="center" colspan="11" bgcolor="#00FF00">Paid By Parish To</td>
        </tr>
        <tr>        
            <td colspan="2">Mortgage/Landlord Name</td>
            <td colspan="2"></td>
            <td>&nbsp;</td><td>&nbsp;</td>
            <td align="center" bgcolor="#00FF00">Check #:</td>
            <td align="center" bgcolor="#00FF00" colspan="2">Amount</td>
            <td>&nbsp;</td><td>&nbsp;</td>
        </tr>
        <tr></tr>
        <tr>
            <td>Street:</td>
            <td colspan="3"></td>
            <td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
            <td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
        </tr>
        <tr>
            <td>City/State:</td>
            <td></td>
            <td>Zip:</td>
            <td></td>
            <td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
            <td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
        </tr>
        <tr></tr>
        <tr>
            <td>&nbsp;</td>
            <td align="center" bgcolor="#00FF00" colspan="3">Utility Name</td>
            <td align="center" bgcolor="#00FF00" colspan="2">Account Number</td>
            <td align="center" bgcolor="#00FF00">Check #</td>
            <td align="center" bgcolor="#00FF00" colspan="2">Amount</td>
            <td>&nbsp;</td><td>&nbsp;</td>
        </tr>
        <tr>
            <td>Electric:</td>
            <td align="center" colspan="3"></td>
            <td align="center" colspan="2"></td>
            <td align="center" ></td>
            <td align="center" colspan="2"></td>
            <td>&nbsp;</td><td>&nbsp;</td>
        </tr>
        <tr>
            <td>Gas:</td>
            <td align="center" colspan="3"></td>
            <td align="center" colspan="2"></td>
            <td align="center" ></td>
            <td align="center" colspan="2"></td>
            <td>&nbsp;</td><td>&nbsp;</td>
        </tr>
        <tr>
            <td>Water:</td>
            <td align="center" colspan="3"></td>
            <td align="center" colspan="2"></td>
            <td align="center" ></td>
            <td align="center" colspan="2"></td>
            <td>&nbsp;</td><td>&nbsp;</td>
        </tr>
        <tr>
            <td>&nbsp;</td><td>&nbsp;</td>
            <td align="right" colspan="5">Parish Check's Total:</td>
            <td colspan="2"></td>
            <td>&nbsp;</td><td>&nbsp;</td>
        </tr>
        <tr>
            <td>&nbsp;</td><td>&nbsp;</td>
            <td align="right" colspan="5">Covered by Conference(Must be atleast 30% of Parish Check:</td>
            <td colspan="2"></td>
            <td>&nbsp;</td><td>&nbsp;</td>
        </tr>
        <tr>
            <td>&nbsp;</td><td>&nbsp;</td>
            <td align="right" colspan="5">Requested from Financial Assistance Fund:</td>
            <td colspan="2"></td>
            <td>&nbsp;</td><td>&nbsp;</td>
        </tr>
        <tr>
            <td>Send Check To:</td>
            <td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
            <td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
            <td>&nbsp;</td><td>&nbsp;</td>
        </tr>
        <tr>
            <td colspan="2">Kathy Clolinger</td>
            <td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
            <td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
        </tr>
        <tr>
            <td colspan="2">2324 Gleneagles Drive</td>
            <td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
            <td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
        </tr>
        <tr>
            <td colspan="2">Naperville, Il 60565</td>
            <td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
            <td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
        </tr>
        <tr>
            <td align="center" bgcolor="#00FF00" colspan="11">**OFFICE USE ONLY: Please Do Not
                                                    Write Below This Line; LEAVE BLANK**</td>
        </tr>
        
    </font></table>
</html>