<table>
    <tr>
        <td>
            <br />Reimbursement Form
        </td>
        <td>
            <br /><?php echo $this->element->report1?> 
        </td>
    </tr>
    <tr>
        <td>
            <br />On Call Activities
        </td>
        <td>
            <br /><?php echo $this->element->report2?> 
        </td>
    </tr>
    <tr>
        <td>
            <br />Client Information
        </td>
        <td>
            <br /><?php echo $this->element->report3?>
        </td>
    </tr>
</table>
 