<form action="<?php echo $this->escape($this->element->getAction()) ?>"
      method="<?php echo $this->escape($this->element->getMethod()) ?>">
      
<table>
    <tr>
        <td>
            <br /><strong>Reimbursement Form</strong>
        </td>
        <td>
            <br />&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $this->element->rReport?> 
        </td>
    </tr>
    <tr>
        <td>
            <br /><strong>On Call Activities</strong>
        </td>
        <td>
            <br />&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $this->element->oReport?> 
        </td>
    </tr>
    <tr>
        <td>
            <br /><strong>Client Information</strong>
        </td>
        <td>
            <br />&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $this->element->cReport?>
        </td>
    </tr>
</table>
</form>