<table border="1">
    <tr>
        <td>&nbsp;</td><td><h3>St. Vincent de Paul</h3></td><td>&nbsp;</td>      
    </tr>
    <tr>
        <td>&nbsp;</td><td><strong>On Call Activities Report</strong></td><td>&nbsp;</td>
    </tr>
    <tr>
        <td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
    </tr>
    <tr>
        <td>&nbsp;Client ID:&nbsp;<?php echo $this->home ?>&nbsp;</td>
    </tr>
</table>