<form action="<?php echo $this->escape($this->element->getAction()) ?>"
      method="<?php echo $this->escape($this->element->getMethod()) ?>">
      
<table>
    <tr>
        <td>
            <br /><h4>Start Date: <?php echo $this->element->startDate?> </h4>
        </td>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
        <td>
            <br /><h4>End Date: <?php echo $this->element->endDate?> </h4>
        </td>
    </tr>
    <tr>
        <td>
            <br /><?php echo $this->element->create?> 
        </td>
    </tr>
</table>
</form>