<table>
    <tr>
        <td>&nbsp;</td><td><h2><center>St. Vincent de Paul&nbsp;&nbsp;</center></h2></td><td>&nbsp;</td>      
    </tr>
    <tr>
        <td>&nbsp;</td><td><h4><center>Reimbursement Report&nbsp;</center></h4></td><td>&nbsp;</td>
    </tr>
    <tr>
        <td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
    </tr>
    <tr>
        <td><strong>Assistance Given To &nbsp;</strong></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
    </tr>
    <tr>        
        <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Created By:&nbsp;<?php echo $this->escape($this->request[0]->getUser())  ?>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
    </tr>
    <tr>        
        <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Name:&nbsp;<?php echo $this->escape($this->client->getFullName())   ?>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
    </tr>
    <tr>        
        <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cell Phone:&nbsp;<?php echo $this->escape($this->client->getFormattedCellPhone())  ?>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
    </tr>
    <tr>        
        <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Home Phone:&nbsp;<?php echo $this->escape($this->client->getFormattedHomePhone())  ?>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
    </tr>
    <tr>        
        <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Work Phone:&nbsp;<?php echo $this->escape($this->client->getFormattedWorkPhone())  ?>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
    </tr>
    <tr>        
        <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Type of Visit:&nbsp;<?php  ?>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
    </tr>
    <tr>        
        <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Visit Date:&nbsp;<?php  ?>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
    </tr>
     <tr>
        <td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
    </tr>
    <tr>
        <td><strong>Paid By Parish To &nbsp;</strong></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
    </tr>
    <?php
        $checkTotal = 0;
        foreach($this->request as $row)
        {
            echo '<tr>';
            echo '<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Payee:&nbsp;';
            echo $this->escape($row->getPayeeName());
            echo '</td><td>&nbsp;</td>';
            echo '</tr>';
            
            echo '<tr>';
            echo '<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Address:&nbsp;';
            echo $this->escape($row->getAddress()->getStreet());
            echo '&nbsp;';echo $this->escape($row->getAddress()->getCity());
            echo '&nbsp;';echo $this->escape($row->getAddress()->getState());
            echo '&nbsp;';echo $this->escape($row->getAddress()->getZip());
            echo '</td><td>&nbsp;</td>';
            echo '</tr>';
            
            echo '<tr>';
            echo '<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Check Amount:&nbsp;';
            echo $this->escape($row->getAmount());
            $checkTotal += $row->getAmount();
            echo '</td><td>&nbsp;</td>';
            echo '</tr>';
            
            echo '<tr>';
            echo '<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Check Number:&nbsp;';
            echo $this->escape($row->getCheckNumber());
            echo '</td><td>&nbsp;</td>';
            echo '</tr>';
            
            echo '<tr>';
            echo '<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Acount Number:&nbsp;';
            echo $this->escape($row->getAccountNumber());
            echo '</td><td>&nbsp;</td>';
            echo '</tr>';
            
            echo '<tr>';
            echo '<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Issue Date:&nbsp;';
            echo $this->escape($row->getIssueDate());
            echo '</td><td>&nbsp;</td>';
            echo '</tr>';
            
            echo '<tr>';
            echo '<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Comments:&nbsp;';
            echo $this->escape($row->getComment());
            echo '</td><td>&nbsp;</td>';
            echo '</tr>';
            
            echo '<tr>';
            echo '<td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>';
            echo '</tr>';
            
            
        }
            echo '<tr>';
            echo '<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Total:&nbsp;';
            echo $this->escape($checkTotal);
            echo '</td><td>&nbsp;</td>';
            echo '</tr>';
    ?>
   
</table>
