<?php $baseUrl = new Zend_View_Helper_BaseUrl();
    $format = new App_Formatting();?>
<table>
    <tr>
        <td><h2><center>St. Vincent de Paul&nbsp;&nbsp;</center></h2></td>
        <td>
            <form action="<?php echo $baseUrl->baseUrl('/report/reimbursepdf/')?>" method=post>
                <input type="hidden" name="caseId" value="<?php echo $this->escape($this->request[0]->getId()) ?>">
                <input type="submit" value="Generate PDF">
            </form>
        </td>
    </tr>
    <tr>
        <td><h4><center>Reimbursement Report&nbsp;</center></h4></td><td>&nbsp;</td>
    </tr>
    <tr>
        <td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
    </tr>
    <tr>
        <td><strong>Assistance Given To &nbsp;</strong></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
    </tr>
    <?php if($this->request[0] != null) ?>
        
    <tr>        
        <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Created By:&nbsp;<?php echo $this->request[0]->getUser()  ?>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
    </tr>
    <tr>        
        <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Name:&nbsp;<?php echo $this->client->getFullName()   ?>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
    </tr>
    <tr>        
        <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cell Phone:&nbsp;<?php echo $this->client->getFormattedCellPhone()  ?>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
    </tr>
    <tr>        
        <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Home Phone:&nbsp;<?php echo $this->client->getFormattedHomePhone()  ?>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
    </tr>
    <tr>        
        <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Work Phone:&nbsp;<?php echo $this->client->getFormattedWorkPhone()  ?>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
    </tr>
    <tr>        
        <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Type of Visit:&nbsp;Home&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
    </tr>
     <tr>
        <td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
    </tr>
    <tr>
        <td><strong>Paid By Parish To &nbsp;</strong></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
    </tr>
    <?php
        $checkTotal = 0;
        foreach($this->request as $row)
        {
            if(strcmp($row->getStatusFull(), "Issued")==0)
            {
                echo '<tr>';
                echo '<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Case Need:&nbsp;';
                echo $this->escape($row->getCaseNeedName());
                echo '</td><td>&nbsp;</td>';
                echo '</tr>';
                
                echo '<tr>';
                echo '<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Payee:&nbsp;';
                echo $this->escape($row->getPayeeName());
                echo '</td><td>&nbsp;</td>';
                echo '</tr>';
                
                echo '<tr>';
                echo '<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Address:&nbsp;';
                echo $this->escape($row->getAddress()->getStreet());
                echo '&nbsp;';echo $this->escape($row->getAddress()->getCity());
                echo '&nbsp;';echo $this->escape($row->getAddress()->getState());
                echo '&nbsp;';echo $this->escape($row->getAddress()->getZip());
                echo '</td><td>&nbsp;</td>';
                echo '</tr>';
                
                echo '<tr>';
                echo '<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Check Amount:&nbsp;';
                echo $format->formatCurrency($this->escape($row->getAmount()));
                $checkTotal += $row->getAmount();
                echo '</td><td>&nbsp;</td>';
                echo '</tr>';
                
                echo '<tr>';
                echo '<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Check Number:&nbsp;';
                echo $this->escape($row->getCheckNumber());
                echo '</td><td>&nbsp;</td>';
                echo '</tr>';
                
                echo '<tr>';
                echo '<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Acount Number:&nbsp;';
                echo $this->escape($row->getAccountNumber());
                echo '</td><td>&nbsp;</td>';
                echo '</tr>';
                
                echo '<tr>';
                echo '<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Issue Date:&nbsp;';
                echo $format->formatDate($this->escape($row->getIssueDate()));
                echo '</td><td>&nbsp;</td>';
                echo '</tr>';
                
                echo '<tr>';
                echo '<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Comments:&nbsp;';
                echo $this->escape($row->getComment());
                echo '</td><td>&nbsp;</td>';
                echo '</tr>';
                
                echo '<tr>';
                echo '<td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>';
                echo '</tr>';
            }
        }
            
            echo '<tr>';
            echo '<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Total:&nbsp;';
            echo $format->formatCurrency($this->escape($checkTotal));
            echo '</td><td>&nbsp;</td>';
            echo '</tr>';
    ?>
   
</table>

<p><br />Excel Reimbursement Form will only include consider the following types:<br />
&nbsp;&nbsp;&nbsp;&nbsp;Rent <br />
&nbsp;&nbsp;&nbsp;&nbsp;Water <br />
&nbsp;&nbsp;&nbsp;&nbsp;Gas <br />
&nbsp;&nbsp;&nbsp;&nbsp;Electric</p>

