<fieldset>
    <legend><?php echo $this->escape($this->legendMsg); ?></legend>
    <?php
    if (isset($this->descriptionMsg)) {
        echo '<p>' . $this->escape($this->descriptionMsg) . '</p>';
    }
    ?>

    <?php echo $this->dirtyField; ?>
    <?php echo $this->removedRecordsField; ?>
    <?php echo $this->removedRecordsHashField; ?>

    <?php if ($this->recordsSubForm->getSubForms()) { ?>
    <table class="table table-striped records<?php if ($this->narrow) { echo ' narrow'; } ?>">
        <tr>
            <?php foreach ($this->labels as $label) { ?>
            <th><?php echo $this->escape($label); ?></th>
            <?php } ?>
            <?php if (!$this->readOnly) { ?>
            <th class=remove></th>
            <?php } ?>
        </tr>
        <?php echo $this->recordsSubForm; ?>
    </table>
    <?php } else { ?>
    <div class=control-group><div class=controls><p class=help-block><?php echo $this->escape($this->noRecordsMsg); ?></p></div></div>
    <?php } ?>

    <?php if ($this->dirty && $this->dirtyMsg) { ?>
    <div class=control-group><div class=controls>
        <p class=help-block><?php echo $this->escape($this->dirtyMsg); ?></p>
    </div></div>
    <?php } ?>
    <?php if (!$this->readOnly) { ?>
    <div class=control-group><div class=controls>
        <?php echo $this->addRecordBtn; ?>
        <?php if (isset($this->submitBtn)) { ?><?php echo $this->submitBtn; ?><?php } ?>
    </div></div>
    <?php } ?>
</fieldset>
