<?php
$editClientUrl = $this->baseUrl(App_Resources::MEMBER . '/editClient/id/'
    . urlencode($this->client->getId()));
$newCaseUrl = $this->baseUrl(App_Resources::MEMBER . '/newCase/clientId/'
    . urlencode($this->client->getId()));
?>
<fieldset>
    <legend>Client summary:</legend>
    <div class=search-results>
        <table class=search-results>
            <?php
            echo $this->partial('partial/searchResultClient.phtml', array(
                'client' => $this->client,
                'noClientLinks' => true,
            ));
            ?>
        </table>
    </div>
    <div class=control-group>
        <div class=controls>
            <a href="<?php echo $this->escape($editClientUrl); ?>" class="btn btn-info">Edit Additional Details</a>
            <a href="<?php echo $this->escape($newCaseUrl); ?>" class="btn btn-success">Open New Case</a>
        </div>
    </div>
</fieldset>

<fieldset>
    <legend>Case history:</legend>
    <?php if ($this->cases) { ?>
    <div class=search-results>
        <table class=search-results>
        <?php
        foreach (array_values($this->cases) as $i => $case) {
            echo $this->partial('partial/searchResultCase.phtml', array(
                'i' => $i,
                'case' => $case,
                'noClientHeader' => true,
            ));
        }
        ?>
        </table>
    </div>
    <?php } else { ?>
    <p>This client has no current or past cases.</p>
    <?php } ?>
</fieldset>
