
<form action="<?= $this->escape($this->element->getAction()) ?>"
      method="<?= $this->escape($this->element->getMethod()) ?>">

<fieldset>
    <table>
    	<tbody>
    		<tr><td>
				<?php echo $this->element->SVDPname ?>
				</td></tr>
				
				<tr><td>
			    <?php echo $this->element->caseID ?>
			    </td>
				<td>
			    <?php echo $this->element->requestDate ?>
			    </td></tr>
				
				<tr><td>
			    <?php echo $this->element->id ?>
			    </td>
				<td>
			    <?php echo $this->element->amount ?>
			    </td></tr>
				
				<tr><td>
			    <?php echo $this->element->payeeName ?>
			    </td>
				<td>
			    <?php echo $this->element->payeeAccount ?>
			    </td>
				</tr>
				
			    <tr><td>
			    <?php echo $this->element->contactfname?>
			    </td>
			    <td>
			    <?php echo $this->element->contactPhone ?>
			    
			    </td></tr>
				
				<tr><td>
				<?php echo $this->element->contactlname ?>	
			    
			    </td>
				<td>
				<?php echo $this->element->checkNum ?>
			    
			    </td></tr>
				
				<tr><td>
				<?php echo $this->element->issueDate ?>
			    </td>
				<td>
				<?php echo $this->element->caseNeed ?>
			    
			    </td></tr>
			    
			    <tr>
			    <td colspan=2>
				<?php echo $this->element->commentText ?>
				</td>
			    </tr>
				

				
		    </tbody>
	    </table>
</fieldset>

<?php foreach( $this->element->getButtons() as $value) { echo $value; } ?>
</form>


