
<form action="<?= $this->escape($this->element->getAction()) ?>"
      method="<?= $this->escape($this->element->getMethod()) ?>">

<fieldset>
    <table>
    	<tbody>
			<tr><td>
				<p> Case Information </p>
				</td></tr>
				
				<tr><td>
				<?php echo $this->element->clientName ?>
				</td><td>
				<?php echo $this->element->SVDPname ?>
				</td></tr>
				
				<tr><td>
			    <?php echo $this->element->caseID ?>
			    </td>
				<td>
			    <?php echo $this->element->caseNeed ?>
			    </td></tr>
				
				<tr><td>
				<p> Contact Information </p>
				</td></tr>

				
				<tr><td>
			    <?php echo $this->element->payeeName ?>
			    </td>
				<td>
			    <?php echo $this->element->payeeAccount ?>
			    </td>
				</tr>
				
				<tr><td>
			    <?php echo $this->element->contactFirst ?>
			    </td>
				<td>
			    <?php echo $this->element->contactLast ?>
			    </td></tr>
				
				<tr><td>
				<?php echo $this->element->contactPhone ?>
				</td>
				<td>
			    <?php echo $this->element->address ?>
			    </td></tr>
				
				<tr><td>
				<p> Check Information </p>
				</td></tr>
				
				<tr><td>
			    <?php echo $this->element->checkID ?>
			    </td>
				<td>
			    <?php echo $this->element->requestDate ?>
			    </td></tr>
				
				<tr><td>
			    <?php echo $this->element->amount ?>
			    </td>
				<td>
			    <?php echo $this->element->issueDate ?>
			    </td></tr>
				
				<tr><td>
			    <?php echo $this->element->checkNum ?>
			    </td>
				<td>
			    <?php echo $this->element->commentText ?>
			    </td></tr>
				
				
		    </tbody>
	    </table>
</fieldset>

<?php echo $this->element->issueCheck ?>
<?php echo $this->element->denyCheck ?>
<?php echo $this->element->editCheck ?>
<?php echo $this->element->addComment ?>
</form>


