<?php
if (empty($this->checkReqs)) {
?>
<p>There are not any open check requests.</p>
<?php
} else {
?>
<p>Here is a summary of currently open check requests.</p>
<div class=search-results>
<table class=search-results>
<?php
foreach (array_values($this->checkReqs) as $i => $checkReq) {
    echo $this->partial('partial/searchResultCheckReq.phtml', array(
        'i' => $i,
        'checkReq' => $checkReq,
    ));
}
?>
</table>
</div>
<?php
}
?>
