
<form action="<?php echo $this->escape($this->element->getAction()) ?>"
      method="<?php echo $this->escape($this->element->getMethod()) ?>"
      class="twocol form-horizontal"
      onsubmit="javascript:return validate_new(this)">

<fieldset class="row-fluid">
    <legend>Check Request</legend>
    
    <div class="span6">
        <?php echo $this->CheckReq->id ?>
    </div>
    
    <div class="span6">
        <?php echo $this->CheckReq->id ?>
    </div>   
     
    <div class="span6">           
        <?php echo $this->CheckReq->id ?>
    </div>

    <div class="span6">
        <?php echo $this->CheckReq->id ?>
    </div>
</fieldset>
<fieldset class="row-fluid">
    <div class="span6">
        <?php echo $this->CheckReq->id ?>
    </div>

    <div class="span6">
        <?php echo $this->CheckReq->id ?>
    </div>

</fieldset>
 <!-- 
    <?php /*echo $this->element->submit ?>
</form>