<a href="<?php echo $this->escape($this->baseUrl('/member')); ?>" class="btn btn-primary btn-large">Open Clients</a>
<a href="<?php echo $this->escape($this->baseUrl('/search/member')); ?>" class="btn btn-primary btn-large">Search</a>
<a href="<?php echo $this->escape($this->baseUrl('/member/maps')); ?>" class="btn btn-primary btn-large">Maps</a>
<a href="<?php echo $this->escape($this->baseUrl('/member/docs')); ?>" class="btn btn-primary btn-large">Documents</a>
<a href="<?php echo $this->escape($this->baseUrl('/member/contact')); ?>" class="btn btn-primary btn-large">Contact</a>
