<?php
// Set page character encoding to Unicode.
$frontController = Zend_Controller_Front::getInstance();
$response        = $frontController->getResponse();
$charset         = $this->getEncoding();

$response->setHeader('Content-type', "text/html; charset=$charset");
$this->headMeta()->setCharset($charset);

// Set the page title.
$this->headTitle($this->pageTitle)
     ->headTitle('Society of St. Vincent de Paul')
     ->setSeparator(' - ');

// Use the main stylesheet.
$this->headLink()->prependStylesheet($this->baseUrl('main.css'), 'all');
$this->headLink()->prependStylesheet(
    'http://ajax.aspnetcdn.com/ajax/jquery.ui/1.8.19/themes/redmond/jquery-ui.css');

// Include jQuery libraries.
$this->headScript()->prependFile($this->baseUrl('main.js'));
$this->headScript()->prependFile($this->baseUrl('jquery.maskedinput-1.3.min.js'));
$this->headScript()->prependFile(
    'http://ajax.aspnetcdn.com/ajax/jquery.ui/1.8.19/jquery-ui.min.js');
$this->headScript()->prependFile('http://ajax.aspnetcdn.com/ajax/jquery/jquery-1.7.2.min.js');

// Render <head> elements.
echo $this->doctype(),    "\n";
echo $this->headMeta(),   "\n";
echo $this->headTitle(),  "\n";
echo $this->headLink(),   "\n";
echo $this->headScript(), "\n";

// Fetch user role for later use.
$auth = Zend_Auth::getInstance();
$role = $auth->hasIdentity() ? $auth->getIdentity()->role : App_Roles::GENERAL;

// Fetch available funds for sidebar.
$config = Zend_Registry::get('config');
$funds  = App_Formatting::formatCurrency($config->getAvailableFunds());

// Fetch user schedule for sidebar.
$scheduleEntries = Zend_Registry::get('schedule');
?>

<div class=container-fluid>
    <div class=navbar>
        <div class=navbar-inner>
            <div class=container>
                <a href="<?php echo $this->escape($this->baseUrl('')); ?>" class=brand>St. Vincent de Paul</a>
                <?php
                    echo $this->partial('partial/navigation.phtml', array(
                        'role' => $role,
                        'nav' => $this->nav,
                    ));
                ?>
            </div>
        </div>
    </div>
</div>

<div class=container-fluid>
    <div class=row-fluid>
        <div class=span2>
            <?php if ($auth->hasIdentity()){ ?>
            <div class="well sidebar-nav">
                <ul class="nav nav-list">
                    <li class=nav-header>Current Funds</li>
                    <li style="text-indent:10px;"><?php echo $this->escape($funds); ?></li>

                    <li class="nav-header">Schedule</li>
                    <?php foreach ($scheduleEntries as $scheduleEntry) { ?>
                    <li><p style="width:200px;">Week of <?php echo $this->escape(App_Formatting::formatDate($scheduleEntry->getStartDate())); ?></p></li>
                    <li><p style="width:150px; text-indent:10px;"><?php echo $this->escape(App_Formatting::truncateString($scheduleEntry->getUser()->getFullName(), 18));?></p></li>
                    <?php } ?>
                    <li class=nav-header>Quick Links</li>
                    <a href="http://www.dupagepads.org">PADS</a><br>
                    <a href="http://www.napervillecares.org">NaperCARES</a><br>
                    <a href="http://www.salvationarmyusa.org/">Salvation Army</a><br>
                    <a href="http://www.loaves-fishes.org">Loaves & Fishes</a><br>
                    <a href="http://www.sharingconnections.org">Sharing Connections</a><br>
                    <a href="http://www.samaritancenter.org">Samaritan Interfaith</a><br>
                    <a href="http://www.napervilletownship.com">LIHeap</a>
                </ul>
            </div>
            <?php } else { ?>
            <p></p>
            <?php } ?>
        </div>

        <div id=zendcontent class=span10>
            <div class=hero-unit>
                <div id=content>
                    <div id=alerts>
                    <?php
                        // Get any unread flash messages.
                        $flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger');

                        if ($flashMessenger->hasCurrentMessages()) {
                            $messages = $flashMessenger->getCurrentMessages();
                            $flashMessenger->clearCurrentMessages();
                        } else {
                            $messages = $flashMessenger->getMessages();
                        }
                        foreach ($messages as $message) {
                            // Write each flash message as a top-level alert.
                            echo '<p class=alert>' . $this->escape($message) . '</p>';
                        }
                    ?>
                    </div>
                    <?php
                        // Write out page content specific to the current controller/action.
                        echo $this->layout()->content;
                    ?>
                </div>
            </div>
        </div>
    </div>

    <hr>

    <footer><p>© 2012 Society of St. Vincent de Paul.</p></footer>
</div>
