
<form action="<?php echo $this->escape($this->element->getAction()) ?>"
      method="<?php echo $this->escape($this->element->getMethod()) ?>">

<fieldset>
    <legend>Welcome! Please Login.</legend>
    
    <?php echo $this->element->username ?>
    <?php echo $this->element->password ?>

</fieldset>
    <?php echo $this->element->err ?>
<table>
    <tr>
        <td>
            <?php echo $this->element->login ?>
        </td>
        <td>
            <?php echo $this->element->forgot ?>
        </td>
    </tr>
</table>
    <?php echo $this->element->prev ?>
</form>