
<form action="<?= $this->escape($this->form->getAction()) ?>"
      method="<?= $this->escape($this->form->getMethod()) ?>">

<fieldset>
    <legend>Editing Client</legend>

    <?= $this->form->clientID ?>
    <?= $this->form->firstName ?>
    <?= $this->form->lastName ?>
    <?= $this->form->otherName ?>
    <?= $this->form->doNotHelp ?>
    <?= $this->form->homePhone ?>
    <?= $this->form->cellPhone ?>
    <?= $this->form->workPhone ?>
    <?= $this->form->address ?>
    <?= $this->form->city ?>
    <?= $this->form->state ?>
    <?= $this->form->zipcode ?>
    <?= $this->form->marriageStatus ?>
    <?= $this->form->spouse ?>
    <?= $this->form->birthdate ?>
    <?= $this->form->ssn4 ?>
    <?= $this->form->veteranFlag ?>
    <?= $this->form->resideParish ?>
    <?= $this->form->memberParish ?>
    <?= $this->form->employer ?>
    <?= $this->form->position ?>
    <?= $this->form->startDate ?>
    <?= $this->form->endDate ?>
    <?= $this->form->createdDate ?>
    <?= $this->form->createdUser ?>
    
</fieldset>

<?= $this->form->submit ?>
</form>