<p>Please enter a search query to find clients and cases.</p>
<?php
echo $this->form;

if (isset($this->clients)) {
    $addClientUrl = $this->baseUrl(App_Resources::MEMBER . '/addClient');

    if (empty($this->clients)) {
?>
<p>
Your search query returned no results.
Would you like to <a href="<?php echo $addClientUrl; ?>">add a new client</a>?
</p>
<?php
    } else {
?>
<table id=search-results>
<?php
        $this->partialLoop()->setObjectKey('client');
        echo $this->partialLoop('partial/searchResultClient.phtml', $this->clients);
?>
</table>
<p>
Client not listed?
Would you like to <a href="<?php echo $addClientUrl; ?>">add a new client</a>?
</p>
<?php
    }
}
?>
