<?php
$viewClientUrl  = $this->baseUrl(App_Resources::MEMBER . '/viewClient/id/'
    . urlencode($this->case->getClient()->getId()));

echo $this->partial('partial/searchResultCommon.phtml', array(
    'rowStripeClass' => 'even',
    'viewClientUrl' => $viewClientUrl,
    'gotoUrl' => $viewClientUrl,
    'gotoLabel' => 'Client',
    'client' => $this->case->getClient(),
));
?>
<tr class="search-result even">
    <th class="search-cell first">Case ID</th>
    <td class=search-cell><?php echo $this->escape($this->case->getId()); ?></td>
    <th class=search-cell>Date</th>
    <td class=search-cell><?php echo $this->escape(App_Formatting::formatDate($this->case->getOpenedDate())); ?></td>
    <th class=search-cell>Status</th>
    <td class=search-cell><?php echo $this->escape($this->case->getStatus()); ?></td>
    <td class="search-cell last"></td>
</tr>
<tr class="search-result even">
    <th class="search-cell bot first">Amount</th>
    <td class="search-cell bot">$<?php echo $this->escape($this->case->getTotalAmount()); ?></td>
    <th class="search-cell bot">Needs</th>
    <td class="search-cell bot"><?php echo $this->escape($this->case->getNeedList()); ?></td>
    <th class="search-cell bot">Member</th>
    <td class="search-cell bot"><?php echo $this->escape($this->case->getOpenedUser()->getFullName()); ?></td>
    <td class="search-cell last"></td>
</tr>
