<?php
$navLinksByRole = array(
    // Navigation for unauthenticated users.
    App_Roles::GENERAL => array(),
    // Navigation for general volunteers.
    App_Roles::MEMBER => array(
        '/member/map' => 'Map',
        '/search/member' => 'Search',
        '/member/openCases' => 'Open Cases',
        '/member/editSchedule' => 'Edit Schedule',
        '/report' => 'Reports',
        '/member/contacts' => 'Contacts',
        '/document/list' => 'Documents',
    ),
    // Navigation for administrators.
    App_Roles::ADMIN => array(
        '/admin/users' => 'Manage Users',
        '/admin/adjust' => 'Adjust Limits',
        '/document/list' => 'Documents',
    ),
    // Navigation for treasurers.
    App_Roles::TREASURER => array(
        '/treasurer' => 'Open Check Requests',
        '/treasurer/updateFunds' => 'Update Current Funds',
        '/search/treasurer' => 'Search',
        '/report' => 'Reports',
        '/document/list' => 'Documents',
    ),
);

// Determine current path for active tab highlighting.
$currentPath = "/{$this->nav['controller']}";

if ($this->nav['action'] !== 'index') {
    $currentPath .= "/{$this->nav['action']}";
}
?>
<ul class=nav>
    <?php
    foreach ($navLinksByRole[$this->role] as $path => $text) {
        echo '<li' . (($path === $currentPath) ? ' class=active' : '') . '>'
           . '<a href="'
           . $this->escape($this->baseUrl($path))
           . '" '
           . '>'
           . $this->escape($text)
           . '</a>'
           . '</li>';
    }
    ?>
</ul>
<?php if ($this->role !== App_Roles::GENERAL) { ?>
<ul class="nav pull-right">
    <li class=divider-vertical></li>
    <li><a href="<?php echo $this->escape($this->baseUrl('/login/logout')); ?>">Logout</a></li>
</ul>
<?php } ?>
