<?php
$clientId     = $this->escape($this->client->getId());

if (isset($this->viewClientUrl)) {
    $preClientId  = '<a href="' . $this->escape($this->viewClientUrl) . '">';
    $postClientId =  '</a>';
} else {
    $preClientId  = '';
    $postClientId = '';
}

if (isset($this->gotoUrl, $this->gotoLabel)) {
    $gotoBtn = '<a href="'
             . $this->escape($this->gotoUrl)
             . '" class="btn btn-mini btn-info">Go to '
             . $this->escape($this->gotoLabel)
             . '</a>';
} else {
    $gotoBtn = '';
}
?>
<?php if (empty($this->noClientHeader)) { ?>
<tr class="search-result <?php echo $this->rowStripeClass; ?>">
    <th class="search-cell top first">Client ID</th>
    <td class="search-cell top id"><?php echo $preClientId, $clientId, $postClientId; ?></td>
    <th class="search-cell top">Name</th>
    <td class="search-cell top name"><?php echo $this->escape($this->client->getFullName()); ?></td>
    <th class="search-cell top">Phone</th>
    <td class="search-cell top"><?php echo $this->escape($this->client->getFormattedPhone()); ?></td>
<?php } ?>
    <td class="search-cell top last"><?php echo $gotoBtn; ?></td>
<?php if (empty($this->noClientHeader)) { ?>
</tr>
<?php } ?>
