<?php
$preClientId  = '<td class="search-cell top id">';
$postClientId = '</td>';
$clientId     = $this->escape($this->client->getId());

$preGotoBtn  = '<td class="search-cell top last">';
$postGotoBtn = '</td>';
$gotoBtn     = '';

if (isset($this->viewClientUrl)) {
    $preClientId  = $preClientId . '<a href="' . $this->escape($this->viewClientUrl) . '">';
    $postClientId =  '</a>' . $postClientId;
}

if (isset($this->gotoUrl, $this->gotoLabel)) {
    $gotoBtn = '<a href="'
             . $this->escape($this->gotoUrl)
             . '" class="btn btn-mini btn-info">Go to '
             . $this->escape($this->gotoLabel)
             . '</a>';
}
?>
<tr class="search-result <?php echo $this->rowStripeClass; ?>">
    <th class='search-cell top first'>Client ID</th>
    <?php echo $preClientId, $clientId, $postClientId; ?>
    <th class='search-cell top'>Name</th>
    <td class='search-cell top name'><?php echo $this->escape($this->client->getFullName()); ?></td>
    <th class='search-cell top'>Phone</th>
    <td class='search-cell top'><?php echo $this->escape($this->client->getFormattedPhone()); ?></td>
    <?php echo $preGotoBtn, $gotoBtn, $postGotoBtn; ?>
</tr>
