<?php
$rowStripeClass = (!(isset($this->i) && $this->i % 2)) ? 'even' : 'odd';
$viewClientUrl  = $this->baseUrl(App_Resources::MEMBER . '/viewClient/id/'
    . urlencode($this->checkReq->getCase()->getClient()->getId()));
$viewCaseUrl    = $this->baseUrl(App_Resources::MEMBER . '/viewCase/id/'
    . urlencode($this->checkReq->getCase()->getId()));
$viewCheckReqUrl = $this->baseUrl(App_Resources::TREASURER . '/checkReq/id/'
    . urlencode($this->checkReq->getId()));

echo $this->partial('partial/searchResultCommon.phtml', array(
    'rowStripeClass' => $rowStripeClass,
    'viewClientUrl' => $viewClientUrl,
    'gotoUrl' => $viewCheckReqUrl,
    'gotoLabel' => 'Request',
    'client' => $this->checkReq->getCase()->getClient(),
));
?>
<tr class='search-result <?php echo $rowStripeClass; ?>'>
    <th class='search-cell first'>Case ID</th>
    <td class=search-cell><a href="<?php echo $this->escape($viewCaseUrl) ?>"><?php echo $this->escape($this->checkReq->getCase()->getId()); ?></a></td>
    <th class=search-cell>Date</th>
    <td class=search-cell><?php echo $this->escape(App_Formatting::formatDate($this->checkReq->getRequestDate())); ?></td>
    <th class=search-cell>Status</th>
    <td class=search-cell><?php echo $this->escape($this->checkReq->getStatusFull()); ?></td>
    <td rowspan=2 class='search-cell last'></td>
</tr>
<tr class='search-result <?php echo $rowStripeClass; ?>'>
    <th class='search-cell bot first'>Request ID</th>
    <td class='search-cell bot'><a href="<?php echo $this->escape($viewCheckReqUrl); ?>"><?php echo $this->escape($this->checkReq->getId()); ?></a></td>
    <th class='search-cell bot first'>Amount</th>
    <td class='search-cell bot'>$<?php echo $this->escape($this->checkReq->getCase()->getTotalAmount()); ?></td>
    <th class='search-cell bot'>Needs</th>
    <td class='search-cell bot'><?php echo $this->escape($this->checkReq->getCase()->getNeedList()); ?></td>
</tr>
