<?php
$rowStripeClass = ($this->partialCounter % 2 == 1) ? 'even' : 'odd';
$viewClientUrl  = $this->baseUrl(App_Resources::MEMBER . '/client/id/'
    . urlencode($this->client->getId()));

echo $this->partial('partial/searchResultCommon.phtml', array(
    'rowStripeClass' => $rowStripeClass,
    'viewClientUrl' => $viewClientUrl,
    'gotoUrl' => $viewClientUrl,
    'gotoLabel' => 'Client',
    'client' => $this->client,
));
?>
<tr class="search-result <?php echo $rowStripeClass; ?>">
    <th class="search-cell bot first">Address</th>
    <td colspan=5 class="search-cell bot"><?php echo $this->escape($this->client->getCurrentAddr()->getFullAddr()); ?></td>
    <td class="search-cell last"><?php if ($this->client->isDoNotHelp()) { ?><span class="label label-important">Do not help</span><?php } ?></td>
</tr>
