<?php if ($this->internal == $this->doc->isInternal()) {

if( $this->doc->isInternal() ) {
    $path = $this->baseUrl(App_Resources::DOCUMENT .'/display/id/' . $this->doc->getId());
}
else
    $path = $this->escape($this->doc->getUrl());
?>

<tr class='search-result'>
    <td class='search-cell'><a href="<?php echo $path?>"> <?php echo $this->escape($this->doc->getName())?></a></th>
    <td class='search-cell last'>
		<?php 
			if ($this->showEditBtn) 
			{ 
				echo "<a href=\"" . $this->escape($this->baseUrl(App_Resources::DOCUMENT 
										.'/delete/id/' . urlencode($this->doc->getId()))) . "\""  
										. "class='btn btn-mini btn-danger deleteDoc' >Delete</a></td>";
			}
		?>
</tr>
<?php } //ends IF($this->internal ...)?>
