
<form action="<?php echo $this->escape($this->element->getAction()) ?>"
      method="<?php echo $this->escape($this->element->getMethod()) ?>"
      id="<?php echo $this->escape($this->element->getName()) ?>">

<fieldset>
    <legend>Adjust Limits</legend>
    
    <?php echo $this->element->aid ?>
    
    <?php echo $this->element->casefund ?>
    <?php echo $this->element->lifetimecases ?>
    <?php echo $this->element->yearlycases ?>
    
</fieldset>
    
    <?php echo $this->element->adjust ?>
</form>