
<form action="<?php echo $this->escape($this->element->getAction()) ?>"
      method="<?php echo $this->escape($this->element->getMethod()) ?>">

<fieldset>
    <legend>Adjust Limits</legend>
    
    <span class="inline"><?php echo $this->element->aid ?></span>
    <?php echo $this->element->casefund ?>
    <?php echo $this->element->lifetimecases ?>
    <?php echo $this->element->yearlycases ?>

</fieldset>
    
    <?php echo $this->element->adjust ?>
</form>