<div class="row">
    <div class="span8">
        <p>Viewing user information</p>
    </div>
    <div class="span4">
        <a href='<?php echo $this->baseUrl('/admin/new');?>'>Add new user</a>
    </div>
</div>
<div class="search-results">
    <table class="search-results">
    
    <?php
    $this->partialLoop()->setObjectKey('user');
    echo $this->partialLoop('partial/viewMemberForAdmin.phtml', $this->users);
    ?>
    
    </table>
</div>

<br />
<a href='<?php echo $this->baseUrl('/admin/new');?>'>Add new user</a>